name: Test Project
on:
  push:
    branches:
      - submission

jobs:
  run_tests:
    name: Run Project Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - name: Clear npm cache
      #   run: npm cache clean --force

      # - name: Install dependencies
      #   run: npm ci

      # - name: Retrieve Collaborators
      #   id: collaborators
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       const response = await github.repos.listCollaborators({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo
      #       });
      #       const collaborators = response.data.map(collaborator => collaborator.login);
      #       console.log(collaborators.join('\n'));
      #     result-encoding: string

      # - name: Set Secret Variable
      #   run: echo "::set-secret name=COLLABORATORS::${{ steps.collaborators.outputs.result }}"

      - name: Run tests
        if: success()
        env:
          GOOGLE_SHEETS_EMAIL: ${{ secrets.GOOGLE_SHEETS_EMAIL }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_EMAIL: ${{ github.event.head_commit.author.email }}
        run: node ./.github/tests/test-projects.js
